spring.profiles.active=prod
spring.freemarker.checkTemplateLocation=false

spring.datasource.url=jdbc:oracle:thin:@//selene.unipago.com.do:1521/SIGMADEV.unipago.com.do
spring.datasource.username=SIGMA
spring.datasource.password=H1$Gx#tl4h5B*R
spring.datasource.driver.class-name=oracle.jdbc.OracleDriver

# dbcp2 settings
# spring.datasource.dbcp2.*

spring.datasource.dbcp2.initial-size=7
spring.datasource.dbcp2.max-total=20
spring.datasource.dbcp2.pool-prepared-statements=true


## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
